# system message
[InfoNotFound]
other = "信息未找到"

[InternalError]
other = "服务器内部错误"

[InvalidArgument]
other = "参数错误"

[Unavailable]
other = "服务器不可用"

# consul resolver
[GrpcConsulResolverStartFail]
other = "启动grpc-consul-resolver失败"

# zap
[FailStartZap]
other = "启动zap失败"

# gorm
[FailStartGorm]
other = "启动gorm失败"

[GormError]
other = "数据库发生错误"

# handler
[FailGetUserList]
other = "获取用户列表失败"

[UserNotFound]
other = "用户不存在"

[UserAlreadyExist]
other = "用户名已存在"

[WrongPassword]
other = "密码错误"

[FailUpdate]
other = "更新失败"


# encrpt pass
[FailMD5]
other = "md5加密失败"